[versions]
kotlin = "2.3.0"
ktorServerTestHostJvm = "3.3.3"
ktorServerWebsockets = "3.3.3"
logback = "1.5.23"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
androidx-datastore = "1.1.7"
exposed = "1.0.0-rc-4"
hikari = "7.0.2"
postgresql = "42.7.7"
flyway = "11.10.5"

[libraries]
a2a-client = { module = "ai.koog:a2a-client" }
a2a-server = { module = "ai.koog:a2a-server" }
agents-features-a2a-client = { module = "ai.koog:agents-features-a2a-client" }
agents-features-a2a-server = { module = "ai.koog:agents-features-a2a-server" }
agents-features-opentelemetry = { module = "ai.koog:agents-features-opentelemetry" }
a2a-transport-client-jsonrpc-http = { module = "ai.koog:a2a-transport-client-jsonrpc-http" }
a2a-transport-server-jsonrpc-http = { module = "ai.koog:a2a-transport-server-jsonrpc-http" }
koog-agents = { module = "ai.koog:koog-agents" }
koog-ktor = { module = "ai.koog:koog-ktor" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
ktor-server-test-host-jvm = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktorServerTestHostJvm" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktorServerWebsockets" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

tool-schema = { module = "com.xemantic.ai:xemantic-ai-tool-schema", version = "1.1.2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
