[versions]
kotlin = "2.3.0"
ktorServerTestHostJvm = "3.3.3"
ktorServerWebsockets = "3.3.3"
logback = "1.5.24"
http4k = "6.25.1.0"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
java-vavr = "0.11.0"
kotlin-vavr = "0.10.2"
arrow = "2.2.1.1"

[libraries]
a2a-client = { module = "ai.koog:a2a-client" }
a2a-server = { module = "ai.koog:a2a-server" }
agents-features-a2a-client = { module = "ai.koog:agents-features-a2a-client" }
agents-features-a2a-server = { module = "ai.koog:agents-features-a2a-server" }
agents-features-opentelemetry = { module = "ai.koog:agents-features-opentelemetry" }
agents-features-memory = { module = "ai.koog:agents-features-memory" }
a2a-transport-client-jsonrpc-http = { module = "ai.koog:a2a-transport-client-jsonrpc-http" }
a2a-transport-server-jsonrpc-http = { module = "ai.koog:a2a-transport-server-jsonrpc-http" }
koog-agents = { module = "ai.koog:koog-agents" }
koog-ktor = { module = "ai.koog:koog-ktor" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
ktor-server-test-host-jvm = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktorServerTestHostJvm" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktorServerWebsockets" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
tool-schema = { module = "com.xemantic.ai:xemantic-ai-tool-schema", version = "1.2.0" }
http4k-bom = { module = "org.http4k:http4k-bom", version.ref = "http4k" }
http4k-core = { module = "org.http4k:http4k-core" }
http4k-client-apache = { module = "org.http4k:http4k-client-apache" }
http4k-format-moshi = { module = "org.http4k:http4k-format-moshi" }
http4k-ai-mcp-sdk = { module = "org.http4k.pro:http4k-ai-mcp-sdk" }
http4k-server-helidon = { module = "org.http4k:http4k-server-helidon" }
http4k-tools-hotreload = { module = "org.http4k.pro:http4k-tools-hotreload" }
java-vavr = { module = "io.vavr:vavr", version.ref = "java-vavr" }
kotlin-vavr = { module = "io.vavr:vavr-kotlin", version.ref = "kotlin-vavr" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
http4k = [
    "http4k-core",
    "http4k-client-apache",
    "http4k-format-moshi",
    "http4k-ai-mcp-sdk",
    "http4k-server-helidon",
    "http4k-tools-hotreload"
]
