app:
  host: "$HOST:0.0.0.0"
  port: "$PORT:8080"

  auth:
    issuer: "$ISSUER:https://accounts.google.com"
    clientId: "$AUTH_CLIENT_ID:ktor-app"
    secret: "$AUTH_CLIENT_SECRET:<empty>"

  openAIKey: "$OPENAI_API_KEY:"
  anthropicKey: "$ANTHROPIC_API_KEY:"

  langfuseUrl: "$LANGFUSE_URL:http://localhost:3000"
  langfusePublicKey: "$LANGFUSE_PUBLIC_KEY:pk-lf-7975f56b-5572-4100-9a04-da53b8743d37"
  langfuseSecretKey: "$LANGFUSE_SECRET_KEY:sk-lf-4acc102c-4e47-4694-a2e5-2e1ee6a0a4da"

  a2aEnabled: "$A2A_ENABLED:true"
  a2aBaseUrl: "$A2A_BASE_URL:http://localhost"
